name: backend-termometro-lasm
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: termometro
      POSTGRES_USER: termometro
      POSTGRES_PASSWORD: termometro
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U termometro -d termometro"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/termometro
      SPRING_DATASOURCE_USERNAME: termometro
      SPRING_DATASOURCE_PASSWORD: termometro
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
volumes:
  pgdata: